# Install directory
cask_args appdir: '/Applications'

# CLIs
brew 'git'
brew 'lazydocker'
brew 'lazygit'
brew 'mongodb-atlas-cli'
brew 'ollama'
brew 'pyenv'
brew 'pyenv-virtualenv'

# GUIs
cask '1password'
cask 'alt-tab'
cask 'appcleaner'
cask 'basecamp'
cask 'docker'
cask 'elgato-control-center'
cask 'google-chrome'
cask 'google-drive'
cask 'grammarly-desktop'
cask 'hey'
cask 'iterm2'
cask 'minecraft'
cask 'mongodb-compass'
cask 'rectangle'
cask 'rider'
cask 'scroll-reverser'
cask 'smoothscroll'
cask 'spotify'
cask 'stats'
cask 'vlc'
cask 'whatsapp'
cask 'zed'
